weets-api-integration
wolox-training/gd-node pull request #2
Opened 2022-05-10 18:12 UTC by gastonmd14

## Summary

Added external API services.

## Known Issues

None

## Trello Card

https://trello.com/c/JN7LuRND/32-servicios-promises-witter

2022-05-10 19:36 UTC, elcorren requested changes
**Nice work**! I indicated only one correction

2022-05-10 19:36 UTC, elcorren commented on app/services/geekJokes.js
> +module.expoorts = {
did you mean "exports" ?

2022-05-10 19:36 UTC, elcorren commented on app/services/geekJokes.js
> +    return axios.get('https://geek-jokes.sameerkumar.website/api?format=json')
Just a comment: Sometimes it is useful to store the URL in a constant to simplify the code readability

2022-05-10 21:10 UTC, gastonmd14 commented on app/services/geekJokes.js
> +module.expoorts = {
Change Ready

2022-05-11 01:05 UTC, yovanny-wolox commented on app/services/geekJokes.js
> +const URL = 'https://geek-jokes.sameerkumar.website/api?format=json';
Disculpen escribir en español.

Quiero compartir algo, esta URL manejada de esta manera funcionará perfecto para el training, sin embargo, es importante tener presente que en un proyecto estos valores es recomendable definirlos en un archivo de configuración o en las variables de entorno. Por ejemplo: en el caso que sea una url que cambie para los diferentes entornos (desarrollo, pruebas, producción) se podrán establecer sin problemas para cada uno de ellos. También esto permitiría reutilizarlo en varios servicios y si existe un cambio este se realizará solo en un lugar.

Me atrevo a explicar con más detalle solo por este PR 🤣 😜 

1. Crear un .env y definir la url:
`WEETS_API_URL=https://geek-jokes.sameerkumar.website/api`

2. En config/index.js se podría agregar algo como lo siguiente en la variable config:
```
common: {
    services: {
        weetsApiUrl: process.env.WEETS_API_URL
    }
}
```
3. En services/geekJokes.js se importa la variable del archivo de configuración, por ejemplo:
```
const {
  common: {
    services: { weetsApiUrl }
  }
} = require('../../config');
```

incluso si deseas, se puede usar solo una parte de ella y concatenar los valores que pienses pueden ser variables en diferentes servicios que lo utilicen
```
const url = `${weetsApiUrl}?format=json`;
```

2022-05-11 11:59 UTC, gastonmd14 commented on app/services/geekJokes.js
> +const URL = 'https://geek-jokes.sameerkumar.website/api?format=json';
Tomo el cambio para tenerlo como buenas practicas.
Cambio realizado.

2022-05-12 13:54 UTC, elcorren approved these changes

2022-05-12 13:59 UTC, yovanny-wolox approved these changes

2022-05-13 12:44 UTC, merged