WIP: Sign up
wolox-training/gd-node pull request #3
Opened 2022-05-12 17:12 UTC by gastonmd14

## Summary

Endpoint to create User POST /Users

## Known Issues

Module.import doesn't work with Emascript6

## Trello Card

https://trello.com/c/sA7x7bhq/35-sign-up

2022-05-13 18:01 UTC, elcorren requested changes

2022-05-13 18:01 UTC, elcorren commented on app/controllers/createUser.js
> +        return res.status(200).json({ Message: 'User created Successfully', Data: user });
Maybe you should return only the user's email and not the entire register?

2022-05-16 10:47 UTC, gastonmd14 commented on app/controllers/createUser.js
> +        return res.status(200).json({ Message: 'User created Successfully', Data: user });
Change applied.

2022-05-16 13:37 UTC, elcorren reviewed
Nice work!

2022-05-16 13:38 UTC, elcorren approved these changes

2022-05-16 15:43 UTC, yovanny-wolox approved these changes

2022-05-16 15:45 UTC, merged